[theme]
primaryColor = "#76B900"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F1"
textColor = "#1A1D17"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
maxUploadSize = 25
